//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5.StoreLocationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StoreLocationService.IStoreLocationService")]
    public interface IStoreLocationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreLocationService/QueryYelpAPI", ReplyAction="http://tempuri.org/IStoreLocationService/QueryYelpAPIResponse")]
        string[] QueryYelpAPI(string term, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreLocationService/QueryYelpAPI", ReplyAction="http://tempuri.org/IStoreLocationService/QueryYelpAPIResponse")]
        System.Threading.Tasks.Task<string[]> QueryYelpAPIAsync(string term, string location);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStoreLocationServiceChannel : Assignment5.StoreLocationService.IStoreLocationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreLocationServiceClient : System.ServiceModel.ClientBase<Assignment5.StoreLocationService.IStoreLocationService>, Assignment5.StoreLocationService.IStoreLocationService {
        
        public StoreLocationServiceClient() {
        }
        
        public StoreLocationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StoreLocationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreLocationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreLocationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] QueryYelpAPI(string term, string location) {
            return base.Channel.QueryYelpAPI(term, location);
        }
        
        public System.Threading.Tasks.Task<string[]> QueryYelpAPIAsync(string term, string location) {
            return base.Channel.QueryYelpAPIAsync(term, location);
        }
    }
}
