//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5.NaturalHazardsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NaturalHazardsService.NaturalHazardsServiceInterface")]
    public interface NaturalHazardsServiceInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NaturalHazardsServiceInterface/NaturalHazards", ReplyAction="http://tempuri.org/NaturalHazardsServiceInterface/NaturalHazardsResponse")]
        double NaturalHazards(double latitude, double longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NaturalHazardsServiceInterface/NaturalHazards", ReplyAction="http://tempuri.org/NaturalHazardsServiceInterface/NaturalHazardsResponse")]
        System.Threading.Tasks.Task<double> NaturalHazardsAsync(double latitude, double longitude);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NaturalHazardsServiceInterfaceChannel : Assignment5.NaturalHazardsService.NaturalHazardsServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NaturalHazardsServiceInterfaceClient : System.ServiceModel.ClientBase<Assignment5.NaturalHazardsService.NaturalHazardsServiceInterface>, Assignment5.NaturalHazardsService.NaturalHazardsServiceInterface {
        
        public NaturalHazardsServiceInterfaceClient() {
        }
        
        public NaturalHazardsServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NaturalHazardsServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NaturalHazardsServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NaturalHazardsServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double NaturalHazards(double latitude, double longitude) {
            return base.Channel.NaturalHazards(latitude, longitude);
        }
        
        public System.Threading.Tasks.Task<double> NaturalHazardsAsync(double latitude, double longitude) {
            return base.Channel.NaturalHazardsAsync(latitude, longitude);
        }
    }
}
