//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5.NewsFocusService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewsFocusService.NewsFocusServiceInterface")]
    public interface NewsFocusServiceInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewsFocusServiceInterface/NewsFocus", ReplyAction="http://tempuri.org/NewsFocusServiceInterface/NewsFocusResponse")]
        string[] NewsFocus(string[] focus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewsFocusServiceInterface/NewsFocus", ReplyAction="http://tempuri.org/NewsFocusServiceInterface/NewsFocusResponse")]
        System.Threading.Tasks.Task<string[]> NewsFocusAsync(string[] focus);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NewsFocusServiceInterfaceChannel : Assignment5.NewsFocusService.NewsFocusServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewsFocusServiceInterfaceClient : System.ServiceModel.ClientBase<Assignment5.NewsFocusService.NewsFocusServiceInterface>, Assignment5.NewsFocusService.NewsFocusServiceInterface {
        
        public NewsFocusServiceInterfaceClient() {
        }
        
        public NewsFocusServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewsFocusServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsFocusServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsFocusServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] NewsFocus(string[] focus) {
            return base.Channel.NewsFocus(focus);
        }
        
        public System.Threading.Tasks.Task<string[]> NewsFocusAsync(string[] focus) {
            return base.Channel.NewsFocusAsync(focus);
        }
    }
}
