//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5.StoreCheckInService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StoreCheckInService.IStoreCheckInService")]
    public interface IStoreCheckInService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreCheckInService/CheckInToStore", ReplyAction="http://tempuri.org/IStoreCheckInService/CheckInToStoreResponse")]
        void CheckInToStore(string name, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreCheckInService/CheckInToStore", ReplyAction="http://tempuri.org/IStoreCheckInService/CheckInToStoreResponse")]
        System.Threading.Tasks.Task CheckInToStoreAsync(string name, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreCheckInService/getListofStores", ReplyAction="http://tempuri.org/IStoreCheckInService/getListofStoresResponse")]
        string[] getListofStores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreCheckInService/getListofStores", ReplyAction="http://tempuri.org/IStoreCheckInService/getListofStoresResponse")]
        System.Threading.Tasks.Task<string[]> getListofStoresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStoreCheckInServiceChannel : Assignment5.StoreCheckInService.IStoreCheckInService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreCheckInServiceClient : System.ServiceModel.ClientBase<Assignment5.StoreCheckInService.IStoreCheckInService>, Assignment5.StoreCheckInService.IStoreCheckInService {
        
        public StoreCheckInServiceClient() {
        }
        
        public StoreCheckInServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StoreCheckInServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreCheckInServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreCheckInServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CheckInToStore(string name, string location) {
            base.Channel.CheckInToStore(name, location);
        }
        
        public System.Threading.Tasks.Task CheckInToStoreAsync(string name, string location) {
            return base.Channel.CheckInToStoreAsync(name, location);
        }
        
        public string[] getListofStores() {
            return base.Channel.getListofStores();
        }
        
        public System.Threading.Tasks.Task<string[]> getListofStoresAsync() {
            return base.Channel.getListofStoresAsync();
        }
    }
}
