//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5.StoreRatingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StoreRatingService.IStoreRatingService")]
    public interface IStoreRatingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreRatingService/QueryYelpAPI", ReplyAction="http://tempuri.org/IStoreRatingService/QueryYelpAPIResponse")]
        string[] QueryYelpAPI(string term, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreRatingService/QueryYelpAPI", ReplyAction="http://tempuri.org/IStoreRatingService/QueryYelpAPIResponse")]
        System.Threading.Tasks.Task<string[]> QueryYelpAPIAsync(string term, string location);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStoreRatingServiceChannel : Assignment5.StoreRatingService.IStoreRatingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreRatingServiceClient : System.ServiceModel.ClientBase<Assignment5.StoreRatingService.IStoreRatingService>, Assignment5.StoreRatingService.IStoreRatingService {
        
        public StoreRatingServiceClient() {
        }
        
        public StoreRatingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StoreRatingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreRatingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreRatingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] QueryYelpAPI(string term, string location) {
            return base.Channel.QueryYelpAPI(term, location);
        }
        
        public System.Threading.Tasks.Task<string[]> QueryYelpAPIAsync(string term, string location) {
            return base.Channel.QueryYelpAPIAsync(term, location);
        }
    }
}
