//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5.StorageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StorageService.StorageInterface")]
    public interface StorageInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StorageInterface/GetData", ReplyAction="http://tempuri.org/StorageInterface/GetDataResponse")]
        string GetData(string key, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StorageInterface/GetData", ReplyAction="http://tempuri.org/StorageInterface/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string key, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StorageInterface/SetData", ReplyAction="http://tempuri.org/StorageInterface/SetDataResponse")]
        string SetData(string key, string password, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StorageInterface/SetData", ReplyAction="http://tempuri.org/StorageInterface/SetDataResponse")]
        System.Threading.Tasks.Task<string> SetDataAsync(string key, string password, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StorageInterface/SetPassword", ReplyAction="http://tempuri.org/StorageInterface/SetPasswordResponse")]
        string SetPassword(string key, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StorageInterface/SetPassword", ReplyAction="http://tempuri.org/StorageInterface/SetPasswordResponse")]
        System.Threading.Tasks.Task<string> SetPasswordAsync(string key, string oldPassword, string newPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StorageInterfaceChannel : Assignment5.StorageService.StorageInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StorageInterfaceClient : System.ServiceModel.ClientBase<Assignment5.StorageService.StorageInterface>, Assignment5.StorageService.StorageInterface {
        
        public StorageInterfaceClient() {
        }
        
        public StorageInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StorageInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(string key, string password) {
            return base.Channel.GetData(key, password);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string key, string password) {
            return base.Channel.GetDataAsync(key, password);
        }
        
        public string SetData(string key, string password, string data) {
            return base.Channel.SetData(key, password, data);
        }
        
        public System.Threading.Tasks.Task<string> SetDataAsync(string key, string password, string data) {
            return base.Channel.SetDataAsync(key, password, data);
        }
        
        public string SetPassword(string key, string oldPassword, string newPassword) {
            return base.Channel.SetPassword(key, oldPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task<string> SetPasswordAsync(string key, string oldPassword, string newPassword) {
            return base.Channel.SetPasswordAsync(key, oldPassword, newPassword);
        }
    }
}
